### ISSUE TITLE
Support clicking on small images?

### ISSUE THREAD

**Issue by klihelp** [cacheflowe/imagexpander#2]
Thanks for the Medium style image popup, looks very nice.

Is it possible to pop a large image when clicking on small image?

**Comment by cacheflowe** [comment]
@klihelp  Do you want to load a higher-res version of the image when you click it? This is a good idea, but it doesn't currently have that feature.

**Comment by klihelp** [comment]
yes. Magnific Popup (https://github.com/dimsemenov/Magnific-Popup) is able to have the zoom function, not sure about the scrolling option..

**Comment by cacheflowe** [comment]
This now works. Instructions are in the README file.
